name: justify_text
description: Returns a list of strings with *exactly* n width length (using monospaced fonts).
version: 0.1.0
homepage: https://github.com/diego-garro/justify-text-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  textwrap: ^1.0.2

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
